Add Association Feature
bushmusi/school-library pull request #3
Opened 2022-05-20 19:29 UTC by bushmusi

> # Below features have been added

- [ ] Set up associations between classes and objects
- [ ] Add `classroom`, `rental`, and `book` file

[**Project requirement**](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_associations.md)

2022-05-20 20:01 UTC, DeliceLydia requested changes
## Hi @bushmusi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project:
- Kudos on the good PR
- Followed git workflow
- No linter errors

## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-20 20:01 UTC, DeliceLydia commented on student.rb
> +    @classroom.add_student(self) unless @classroom.students.include?(self)
- [ ] This is a `belongs_to` side(a student belongs to a classroom) you can use `students.push(self)`:
`classroom.students.push(self) unless classroom.students.include?(self)`

2022-05-20 20:01 UTC, DeliceLydia commented on book.rb
> +  attr_reader :rentals
- [ ] I suggest that you use `rentals` as `attr_accessor` as well

2022-05-20 20:01 UTC, DeliceLydia commented on rental.rb
> +  attr_reader :person, :book
- [ ] I suggest that you use `person` and `book` as `attr_accessor` to be able to access and modify them at the same time

2022-05-20 20:01 UTC, DeliceLydia commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Please make `rentals` as `attr_accessor` as well to be able to access them and modify them at the same time

2022-05-20 20:09 UTC, bushmusi commented on book.rb
> +  attr_reader :rentals
Understood and improved

2022-05-20 20:11 UTC, bushmusi commented on person.rb
> +  attr_reader :id, :rentals
Thanks and solved

2022-05-20 20:12 UTC, bushmusi commented on rental.rb
> +  attr_reader :person, :book
Thanks and solved

2022-05-20 20:15 UTC, GzimAsani requested changes
Hi @bushmusi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-21 08:52 UTC, Whoistolu commented on student.rb
> +    @classroom.add_student(self) unless @classroom.students.include?(self)
Well resolved 👍🏽

2022-05-21 08:53 UTC, Whoistolu commented on book.rb
> +  attr_reader :rentals
Well resolved 👍🏽

2022-05-21 08:54 UTC, Whoistolu commented on rental.rb
> +  attr_reader :person, :book
Well resolved 👍🏽

2022-05-21 08:54 UTC, Whoistolu commented on person.rb
> +  attr_reader :id, :rentals
Well resolved 👍🏽

2022-05-21 08:55 UTC, Whoistolu approved these changes
### Hi @bushmusi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 08:57 UTC, bushmusi commented
> ### Hi @bushmusi
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> 
> # STATUS: APPROVED 
> **Congratulations! tada**
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Whoistolu in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks @Whoistolu

2022-05-21 08:57 UTC, merged